# Generated by Django 4.2.8 on 2023-12-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contact_product_form_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='messsage',
            field=models.TextField(),
        ),
    ]
