# Generated by Django 4.2.8 on 2023-12-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_contact_messsage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='messsage',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
