# Generated by Django 4.2.8 on 2023-12-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_contact_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Contact information'},
        ),
        migrations.AlterModelOptions(
            name='product_form',
            options={'verbose_name_plural': 'product enquiry'},
        ),
        migrations.AddField(
            model_name='contact',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product_form',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
