# Generated by Django 4.2.8 on 2023-12-24 14:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_contact_options_alter_product_form_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product_form',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
