# Generated by Django 4.2.8 on 2023-12-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_customer_name_product_form_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_form',
            name='period',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
